#!/usr/bin/env python

import yaml
import sys
import os

import datetime
from time import gmtime, strftime, sleep

from modules.config_parser import args
from modules.counter import Counter
from modules.ho import HTTPOperation
from modules.helpers import get_hexdec_combos


config = yaml.safe_load(open(args.config))
if (args.data != ""):
    config["source_data"] = args.data
    
print()
print("Config:")
print(config)
print()

counter = Counter()
http_ops = HTTPOperation(config, counter)

uris = []
pairtrees = []
with open(config["source_data"]) as f:
    lines = f.readlines()
    for l in lines:
        l_parts = l.split(';')
        
        uri = l_parts[0]
        uris.append(uri)
        
        if not 'addison' in uri:
            pairtree = '/'.join(uri.split('/')[:-1])
            pairtrees.append(pairtree)
pairtree_set = set(pairtrees)
pairtrees = list(pairtree_set)

st = datetime.datetime.now()
starttime = strftime("%Y-%m-%d %H:%M:%S", gmtime())

for u in uris:
    http_ops.get_request(u)
for pt in pairtrees:
    http_ops.get_request(pt)

endtime = strftime("%Y-%m-%d %H:%M:%S", gmtime())
et = datetime.datetime.now()
timedelta = et - st

counter.output(starttime, endtime, timedelta, config["load_binary_data"])



